set(FRAMEWORK_IDENTIFIER "com.${MODULE_NAME}")
set(FRAMEWORK_VERSION 1.0.0)

set_target_properties("${MODULE_NAME}" PROPERTIES
  FRAMEWORK TRUE
  FRAMEWORK_VERSION A
  PUBLIC_HEADER "${HEADERS}"
  VERSION "${FRAMEWORK_VERSION}"
  SOVERSION "${FRAMEWORK_VERSION}"
  MACOSX_FRAMEWORK_BUNDLE_VERSION "${FRAMEWORK_VERSION}"
  MACOSX_FRAMEWORK_SHORT_VERSION_STRING "${FRAMEWORK_VERSION}"
  MACOSX_FRAMEWORK_IDENTIFIER "${FRAMEWORK_IDENTIFIER}"
  MACOSX_FRAMEWORK_INFO_PLIST "${CMAKE_CURRENT_LIST_DIR}/../Info.plist"
  XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "13.0"
  XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT "dwarf-with-dsym"
  XCODE_ATTRIBUTE_ALWAYS_SEARCH_USER_PATHS "NO"
)
