set(OPENSSL_PATH "/opt/homebrew/opt/openssl@3")
set(DEPS_DIR "${CMAKE_CURRENT_LIST_DIR}/../_deps/${CMAKE_GENERATOR}")

# Add OpenSSL directories
set(OPENSSL_ROOT_DIR ${OPENSSL_PATH})
set(OPENSSL_INCLUDE_DIR ${OPENSSL_PATH}/include)
set(OPENSSL_LIBRARIES ${OPENSSL_PATH}/lib)
set(OPENSSL_SSL_LIBRARY ${OPENSSL_LIBRARIES})
set(OPENSSL_CRYPTO_LIBRARY ${OPENSSL_LIBRARIES})

# FetchContent options
set(FETCHCONTENT_BASE_DIR ${DEPS_DIR})  # Shared dependency directory

# CXX options
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Custom options
# set(CMAKE_MESSAGE_LOG_LEVEL WARNING)
set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_EXPORT_COMPILE_COMMANDS 1)
set(CODE_SIGNING_ALLOWED "NO")
set(REALM_CPP_NO_TESTS "ON")
set(REALM_CPP_USE_SYSTEM_OPENSSL "ON")
set(REALM_DISABLE_ALIGNED_STORAGE 1)
add_compile_definitions(FORCE_POSIX)
