target 'example-ios' do
  platform :ios, '13'
  pod 'AppCore', :path => '../../packages/AppCore/AppCore.podspec'
end

target 'example-macos' do
  platform :macos, '10.15'
  pod 'AppCore', :path => '../../packages/AppCore/AppCore.podspec'
end
